from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import darkblue
from reportlab.lib.units import inch

from datetime import datetime


# ==========================================
# Create Medicine PDF Report
# ==========================================

def create_pdf(report_text, filename="Medicine_Report.pdf"):

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = darkblue

    heading_style = styles["Heading2"]

    body_style = styles["BodyText"]

    doc = SimpleDocTemplate(filename)

    story = []

    # -------------------------------
    # Title
    # -------------------------------

    story.append(
        Paragraph(
            "💊 PillVision AI Report",
            title_style
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # -------------------------------
    # Date
    # -------------------------------

    story.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",
            body_style
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    # -------------------------------
    # AI Report
    # -------------------------------

    story.append(
        Paragraph(
            "<b>Medicine Analysis</b>",
            heading_style
        )
    )

    story.append(Spacer(1, 0.1 * inch))

    report_text = report_text.replace("\n", "<br/>")

    story.append(
        Paragraph(
            report_text,
            body_style
        )
    )

    story.append(Spacer(1, 0.3 * inch))

    # -------------------------------
    # Disclaimer
    # -------------------------------

    story.append(
        Paragraph(
            "<b>Disclaimer</b>",
            heading_style
        )
    )

    story.append(
        Paragraph(
            "This report is generated by PillVision AI for educational purposes only. "
            "Always consult a qualified healthcare professional before taking or changing any medicine.",
            body_style
        )
    )

    doc.build(story)

    return filename
