import streamlit as st

from utils.gemini import drug_interaction
from utils.history import add_history
from utils.pdf import create_pdf

st.set_page_config(
    page_title="Drug Interaction Checker",
    page_icon="⚠️",
    layout="wide"
)

st.title("⚠️ Drug Interaction Checker")

st.write("""
Check possible interactions between two medicines.

Example:

Medicine 1: Dolo 650

Medicine 2: Ibuprofen
""")

col1, col2 = st.columns(2)

with col1:
    medicine1 = st.text_input(
        "💊 Medicine 1",
        placeholder="Example: Dolo 650"
    )

with col2:
    medicine2 = st.text_input(
        "💊 Medicine 2",
        placeholder="Example: Ibuprofen"
    )

st.markdown("---")

if st.button("🔍 Check Interaction", use_container_width=True):

    if medicine1.strip() == "" or medicine2.strip() == "":

        st.warning("Please enter both medicine names.")

    else:

        with st.spinner("Checking interaction..."):

            try:

                result = drug_interaction(
                    medicine1,
                    medicine2
                )

                add_history(
                    "Drug Interaction",
                    f"{medicine1} + {medicine2}",
                    result
                )

                st.success("✅ Analysis Completed")

                st.markdown(result)

                pdf_file = create_pdf(result)

                with open(pdf_file, "rb") as file:

                    st.download_button(
                        "📄 Download Report",
                        data=file,
                        file_name="Drug_Interaction_Report.pdf",
                        mime="application/pdf",
                        use_container_width=True
                    )

            except Exception as e:

                st.error("Unable to analyze interaction.")

                st.exception(e)

st.markdown("---")

st.subheader("🧪 Try These Examples")

col1, col2 = st.columns(2)

with col1:

    st.info("""
💊 Paracetamol

+

Ibuprofen
""")

    st.info("""
💊 Cetirizine

+

Alcohol
""")

with col2:

    st.info("""
💊 Warfarin

+

Aspirin
""")

    st.info("""
💊 Amoxicillin

+

Paracetamol
""")

st.markdown("---")

st.warning("""
⚠️ Disclaimer

Drug interaction information is generated by AI for educational purposes.

Always consult your doctor or pharmacist before combining medicines.
""")
